### ISSUE TITLE
Infinite loop when trying to figure out the next page

### ISSUE THREAD

**Issue by nikhilsi** [marek-stoj/NReadability#7] opened 2012-04-17 14:10 UTC
example URL: http://www.nytimes.com/2012/04/08/magazine/jack-white-is-the-savviest-rock-star-of-our-time.html?partner=rss&emc=rss.

Basically, the r=1 parameter keeps changing on each next page move and the system assumes that's a different URL.

The fix I was thinking was to try to get all pages in the Transcode function and then parse those pages.

**Comment by marek-stoj** [comment] 2012-04-17 14:24
Can't reproduce. What 'r' parameter? Could you create a unit test that shows this behavior?

**Comment by nikhilsi** [comment] 2012-04-17 20:38
I will do that soon

**Comment by marek-stoj** [comment] 2012-04-27 08:37
Any progress on this test case?

**Comment by hempels** [comment] 2012-06-11 02:05
I believe I've resolved this issue, although I didn't commit a fix because it can be fixed by overriding the default IUrlFetcher implementation.

The issue with NYT appears to be that they rely on Cookies to determine which "_r=" parameter value to use for navigation URLs. It isn't clear to me why they do this, but it's unimportant. The important point is that enabling session cookies by the URL Fetcher solves the problem.

I simply implemented a new version of IURLFetcher and pass it into the constructor.

``` c#
class UrlFetcherWithCookies : IUrlFetcher
{
    // Create one container instance (so the same cookies are passed for each page requested)
    private CookieContainer _cookieContainer = new CookieContainer();

    public string Fetch(string url)
    {
        var fetchRequest = (HttpWebRequest)WebRequest.Create(url);
        // Provide the cookie container instance for each request
        fetchRequest.CookieContainer = _cookieContainer;
        fetchRequest.Method = "GET";

        using (var resp = fetchRequest.GetResponse())
        using (var reader = new StreamReader(resp.GetResponseStream(), true))
        {
            return reader.ReadToEnd();
        }
    }
}
```

**Comment by marek-stoj** [comment] 2012-06-24 07:38
Thanks! I've updated the UrlFetcher implementation (it now uses cookies and also supports compressed responses).

**Closed as completed by marek-stoj** 2012-06-24 07:39 UTC
